### ISSUE TITLE
Can't make the demoApp example run

### ISSUE THREAD

**Issue by Yohannfra** [seongji-SFM/SFM_15x#1]
Hi,
I'm trying to run the demoApp example but it gives me the following message in RTTViewer.
```
00> 00
00> ====== SFM200 Module Started Ver:300 bdtype:1 ======
00> 00 build date: Sep 24 2019, 13:19:19
00> 00 Check Reset Reason:0x0000000C
00> 00 SW_Reset_Det
00> 00 LOCKUP_Det
00> 02 bootstrap pin lv1: dl1, scl:0, sda:0
00> 10 bootloader Not detected!
00> 00 BL ADDR [mbr:FFFFFFFF, uicr:FFFFFFFF]
00> 00 === warning SDA is Low! make CLK, stop ==

```
I'm using Segger embedded studio on Windows 10 to compile and flash.

Thanks for your help.

**Comment by smarthomeagentur** [comment]
You need to compile and flash the bootloader. its also in the folders named "demoBootloader"
Also what module are u using? maybe you need to define it in the file "cfg_config_module.h"

**Comment by Yohannfra** [comment]
Thanks you @smarthomeagentur that was it, it works now :)
