### ISSUE TITLE
demoApp execution stops

### ISSUE THREAD

**Issue by Yohannfra** [seongji-SFM/SFM_15x#10]
Hello i'm facing an issue with the demo app, many times after i flash it it's execution stop in the init and i doesn't start again. and a few time after a few reflash it magicly works again.

the output i have is :
```
====== SFM20R Module Started Ver:300 bdtype:1======
00 build date:Nov 13 2019, 14:51:10
00 Check Reset Reason:0x00000001
00 HW_Reset_Det! (POR)
02 bootstrap pin lvl: dl:1, scl:0, sda:0
08 bootloader detected:00075000
00 BL ADDR [mbr:00075000, uicr:FFFFFFFF]
00 
```
and after that nothing...

after some debug i found out that the execution stop in : 
main -> cfg_board_early_init -> cfg_i2c_master_send_General_Call_Reset 

this is the function
```c

uint32_t cfg_i2c_master_send_General_Call_Reset(void)
{
    uint32_t timeout;
    uint8_t array[4];
    
    spi_xfer_done = false;
    timeout = 100000;
    array[0] = 0x06;
    APP_ERROR_CHECK(nrf_drv_twi_tx(&m_twi, 0, array, 1, false));
	while((!spi_xfer_done) && --timeout);	
    if(!timeout) return NRF_ERROR_TIMEOUT;
    nrf_delay_ms(1);
    return NRF_SUCCESS;
}
```
it stops just after the while , do you have an idea why and how to make it work ?

Thanks

**Comment by Yohannfra** [comment]
Any idea @yepark-wisol ?

**Comment by yepark-wisol** [comment]
Please explain the situation in more detail.
Is the reboot repeated?
After flash writing with J-Link, press the Reset key once.
