### ISSUE TITLE
G Sensor Callback not existing

### ISSUE THREAD

**Issue by smarthomeagentur** [seongji-SFM/SFM_15x#2]
Hi,
I want to use a callback function for g sensor action. the setup works and with some register changes it detects motion in log with "g-sensor shaking". So there must be a callback but its not usable because there is no .c code for bma250.
In the SFM Architecture guide the function "static void bma250_state_handler(void * p_context)" is mentioned but it also does not trigger on motion. So could you please descripte how to get the motion callback working?

Thanks and best regards
Daniel

**Comment by yepark-wisol** [comment]
The bma250 related library is not open by policy.
Develop yourself by referring to the datasheet.
development/SFM/documentation/datasheet
   -> BST-BMA250E-DS004-06.pdf or BST-BMP280-DS001-11.pdf

**Comment by smarthomeagentur** [comment]
Hi @yepark-wisol . I mean yes, i could. But whats the use of a module with sdk when I can´t use its features? I mean even in the datasheet of the module you name it with ACC Sensor and this is useless if its not feature of the own sdk. Could you agree with this? Maybe you can implement this feature, if you are not willing to share parts of the code.

Thanks and best regards

daniel
