### ISSUE TITLE
Get all Wifi results from scan

### ISSUE THREAD

**Issue by smarthomeagentur** [seongji-SFM/SFM_15x#3]
Hi,
I did a request before and now ask again why there are no options to get more then the predefined number of mac adresses from wifi scan? The whitelist does not help in most cases. Only one case is if I want to exclude wifis via wildcard.
I would really love to get all the results for processing.

Thanks in advance.

Daniel

**Comment by yepark-wisol** [comment]
The API is not supported, but you can be solved with bypass mode.
WIFI is controlled by the AT command. For the AT command set, refer to the following document.
https://github.com/seongji-SFM/SFM_15x/blob/master/development/SFM/documentation/datasheet/4a-esp8266_at_instruction_set_en_v31.pdf
For example, The scan command is "AT+CWLAP\r\n".
