### ISSUE TITLE
GPS Timeout Setter not working

### ISSUE THREAD

**Issue by smarthomeagentur** [seongji-SFM/SFM_15x#4]
I set the GPS Timeout and get the value back via:
`cPrintLog(CDBG_MAIN_LOG, "GPS %d\n", gps_tracking_get_interval(module_parameter_item_gps_tracking_time_sec));`
If I then start GPS via start_gps_tracking() I get a timeout after 10 Sec. with Output:
`GPS Acqusition Stop. C/N0 Low! Time Out(10 sec)! C/N0[0]dB-Hz `

**Comment by smarthomeagentur** [comment]
In the header file I found this enum:
{
    CGPS_SMART_MODE = 0,
    CGPS_MANUAL_MODE,
    CGPS_MODE_MAX
}CGPS_OPERATION_MODE_e;

Maybe this is the reason but there is no documentation how to change the GPS Mode

**Comment by smarthomeagentur** [comment]
It´s possible to disable "smart tracking via `module_parameter_set_val(module_parameter_item_gps_operation_mode,1);` This should be documented, also the default settings should be documented.

**Comment by crazyday** [comment]
documentation is not the strong point of wisol

**Comment by crazyday** [comment]
@smarthomeagentur  Does GPS module give a result ? On BRKWS20 board, we only have errors GPS not fixed
