### ISSUE TITLE
Error on BRKWS20

### ISSUE THREAD

**Issue by crazyday** [seongji-SFM/SFM_15x#6]
I'm testing BRKWS20 board that contains the SFM20R1 microcontroller with the demoapp.

The result is an error on GPS : 
14 GPS Acqusition Stop. C/N0 Low! Time Out(10 sec)! C/N0[0]dB-Hz 

Does anyone have a solution ?

Thanks

**Comment by Yohannfra** [comment]
I have the same issue. In the last version of the sdk the time out was set to 60 secs, it maybe that but i'm not sure and i haven't try yet

**Comment by crazyday** [comment]
is there SDK documentation available?

**Comment by yepark-wisol** [comment]
GPS_OPERATION_MODE_DEFAULT to 1 (CGPS_MANUAL_MODE)
change CDEV_FS_VER or use factory_write (development\SFM\binary\development\SFM\binary)
Use GPS antennas with active antennas.

**Comment by crazyday** [comment]
Same error

**Comment by crazyday** [comment]
your answer is incomprehensible. Change CDEV_FS_VER by what ?

Your SFM20R1 module is poorly documented. Your SDK doesn't work. I don't understand that Sigfox refers you.

Why closing the issue, it's not resolved ?

**Comment by yepark-wisol** [comment]
It is about the initial default value of the setting value for GPS operation.
The setting will be retained and will be initialized when the FS version changes or Erases.
Change the default value of GPS_OPERATION_MODE_DEFAULT to change the define value. After that, run "download_Factory.cmd" or change "CDEV_FS_VER" to apply it.
CDEV_FS_VER is the version value of the setting area.

**Comment by crazyday** [comment]
This solution is not working 
14 GPS Position Not Fixed! tracking_time[75]sec C/N0[0]dB-Hz

**Comment by Yohannfra** [comment]
We should not have to ask those questions, this should be documented..

**Comment by crazyday** [comment]
Ca je suis bien d'accord. Travailles-tu sur la BRKWS20 ?

**Comment by Yohannfra** [comment]
Oui, je peux avoir ton mail ou quelque chose pour te contacter ?

**Comment by crazyday** [comment]
abourrat@free.fr, je t'enverrai mon numéro par mail

**Comment by yepark-wisol** [comment]
Please check the GPS antenna.

**Comment by Yohannfra** [comment]
@yepark-wisol  the GPS antenna is fine, it's not about it. I tried your solution and i still have the same error : 
```
...
00> 02 GPS Start
 00> 14 GPS Position Not Fixed! tracking_time[90]sec C/N0[25]dB-Hz 
...
```
Something is clearly not working.
Would a full log of the demoMain help you to help us ?

Thanks.

**Comment by yepark-wisol** [comment]
The GPS ran for 90 seconds but failed to position fix.
Check the antenna.
This cannot be helped by software.

**Comment by yepark-wisol** [comment]
Is it correct to use an active antenna?
Did you test it on the out door?

**Comment by crazyday** [comment]
Yes, in the BRKWS, it's an active antenna. I tested with another active antenna, the result is the same. I test both indoor and outdoor.

Either the gps module of the controller wssfm20r1 does not work, or it comes from the code.

Strangely, the result is the same on version 12 of the SDK.

**Comment by Yohannfra** [comment]
I just tried the gps outdoor and it works thanks @yepark-wisol . 
That's still strange that it does not fix when i'm indoor but it's not software anyway.
