### ISSUE TITLE
Manual is not up to date

### ISSUE THREAD

**Issue by Yohannfra** [seongji-SFM/SFM_15x#7]
Hi, the manual in **development/SFM/documentation/manual/[SEONGJI]AppNote_SFM_Architecture_of_SW_V300.pdf** is not up to date. Some functions presented as the api don't exists in the sdk, could you please update it to provide a clear manual of the api.
thanks

**Comment by Yohannfra** [comment]
@yepark-wisol can you explain why you closed it ?

**Comment by yepark-wisol** [comment]
We can't contain everything in a document.
The SDK is a demo that can be used to develop a device.
We recommend referencing the source.

**Comment by Yohannfra** [comment]
Sure i know that you can't contain everything in a document, that was not what i wanted to say. i just wanted to warn you that the documentation is not up to date, it's still referring to the last version of the sdk  (SFM_12x).

Ps: Is the this version of the sdk in it's final form or you plan to add stuff ? I'm using it for work and not sure if it's 100% done with everything stable

Thanks.

**Comment by yepark-wisol** [comment]
The BRKWS20 board hasn't been tested (It's not what we made)
We also have EVB and Demo Device (iHere).
S/W is considered stable, and there are no plans to update the SDK not yet.
