### ISSUE TITLE
Differences beetween this sdk and the SFM_12x sdk

### ISSUE THREAD

**Issue by Yohannfra** [seongji-SFM/SFM_15x#8]
I'm asking this question to know what reasons made you create a new sdk, what are the main differences beetween this sdk and the SFM_12x sdk and why should we use this one instead of the SFM_12x sdk

thanks

**Comment by yepark-wisol** [comment]
nrf52 SDK Version Up to "nRF5 SDK v15.3.0" (support BLE5.0).
  ->  https://infocenter.nordicsemi.com : nrf52832
Source file structure change. 
thanks.
